updates done by...

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -18,7 +18,7 @@ on:
         type: choice
         options:
           - ubuntu-latest
-          - ubuntu-22.04
+          - ubuntu-22.04-local
         default: ubuntu-latest
       lto_type:
         description: "Choose LTO type (full will not run on basic runners)"
@@ -73,17 +73,17 @@ jobs:
       REPO_OWNER: ahmad24shargh
       REPO_NAME: Gki-kernel-with-ksu-next-susfs
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      RELEASE_NAME: "*TEST BUILD* GKI Kernels With KernelSU ${{ inputs.kernelsu_variant }} & SUSFS v1.5.5 *TEST BUILD*"
+      RELEASE_NAME: "*TEST BUILD* GKI Kernels With KernelSU-${{ inputs.kernelsu_variant }} ${{ inputs.kernelsu_branch }} & SUSFS v1.5.5 *TEST BUILD*"
       RELEASE_NOTES: |
-        This release contains KernelSU ${{ inputs.kernelsu_variant }} and SUSFS v1.5.5
+        This release contains KernelSU-${{ inputs.kernelsu_variant }} ${{ inputs.kernelsu_branch }} and SUSFS v1.5.5
         
         Features:
-        [+] KernelSU-${{ inputs.kernelsu_variant }}
-        [+] SUSFS ඞ v1.5.5 
-        [+] Wireguard Support
-        [+] Simple Maphide for LineageOS Detections
-        [+] Futile Maphide for jit-zygote-cache Detections
-        [+] Magic Mount Support
+        -> KernelSU-${{ inputs.kernelsu_variant }}-${{ inputs.kernelsu_branch }}
+        -> SUSFS ඞ v1.5.5 
+        -> Wireguard Support
+        -> Simple Maphide for LineageOS Detections
+        -> Futile Maphide for jit-zygote-cache Detections
+        -> Magic Mount Support
 
         Module: 
         -> https://github.com/sidex15/ksu_module_susfs
@@ -94,7 +94,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Determine the branch for KernelSU-${{ inputs.kernelsu_variant }}
-        if: ${{ inputs.kernelsu_branch == 'Dev' }}
+        if: ${{ inputs.kernelsu_branch == 'Dev' || inputs.kernelsu_variant == 'MKSU' }}
         run: |
           # Determine the branch based on user input
           if [[ "${{ inputs.kernelsu_variant }}" == "Official" || "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
@@ -129,31 +129,29 @@ jobs:
             echo "Unknown variant"
           fi
           
-          BRANCH="${{ env.KSU_BRANCH }}"
-          
-          if [[ ${{ inputs.kernelsu_branch }} == "Stable" && "${{ inputs.kernelsu_variant }}" != "MKSU" ]]; then
+          if [[ "${{ inputs.kernelsu_branch }}" == "Stable" && "${{ inputs.kernelsu_variant }}" != "MKSU" ]]; then
             # Fetch the latest tag
             TAG=$(git ls-remote --tags --sort=-v:refname $REPO_URL | grep -o 'refs/tags/.*' | cut -d'/' -f3 | head -n1)
             if [[ -z "$TAG" ]]; then
-              echo "Error: Could not fetch latest tag for KernelSU" >&2
+              echo "Error: Could not fetch latest tag for Stable" >&2
               exit 1
             fi
             KSU_REF=$TAG
             KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
 
-          elif [[ ${{ inputs.kernelsu_branch }} == "Dev" || "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Dev" || "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
             # Fetch the latest commit from "next" branch
-            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$BRANCH | awk '{ print $1 }')
+            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$KSU_BRANCH | awk '{ print $1 }')
             if [[ -z "$COMMIT_HASH" ]]; then
-              echo "Error: Could not fetch latest commit for KernelSU-Next Dev" >&2
+              echo "Error: Could not fetch latest commit for Dev" >&2
               exit 1
             fi
             KSU_REF=$COMMIT_HASH
             KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
 
           else
-            # Fetch the specific tag for the custom branch
-            TAG=$BRANCH
+            # Fetch the specific tag
+            TAG=${{ inputs.kernelsu_branch_other }}
             if git ls-remote --tags $REPO_URL | grep -q "refs/tags/$TAG"; then
               KSU_REF=$TAG
               KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
@@ -175,7 +173,7 @@ jobs:
           GITLAB_REPO="susfs4ksu"
 
           declare -A BRANCH_MAP=(
-          	["gki_android13_5_15"]="gki-android13-5.15"
+            ["gki_android13_5_15"]="gki-android13-5.15"
           )
 
           for var_name in "${!BRANCH_MAP[@]}"; do
@@ -227,7 +225,7 @@ jobs:
           echo "" >> $GITHUB_ENV
           echo "LTO: ${{ inputs.lto_type }}" >> $GITHUB_ENV
           echo "" >> $GITHUB_ENV
-          echo "Commit Hashes & Links:" >> $GITHUB_ENV
+          echo "Commit Hashes and Links:" >> $GITHUB_ENV
           echo "KernelSU:" >> $GITHUB_ENV
           echo "${{ inputs.kernelsu_variant }}-${{ inputs.kernelsu_branch }}: [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
           echo "SUSFS4KSU:" >> $GITHUB_ENV
@@ -256,7 +254,7 @@ jobs:
 
             # Create the tag in the repository
             git tag $NEW_TAG
-            git push origin $NEW_TAG
+            git push --tags
             
       # Download Artifacts for A12 (Only if A12 Build is successful or input is true or empty)
       - name: Download Artifacts
@@ -292,3 +290,5 @@ jobs:
         run: |
           echo "GitHub release created with the following files:"
           ls ./downloaded-artifacts/**/*
+
+      
