Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -380,17 +380,21 @@ jobs:
           sudo apt-get --assume-yes update
           sudo apt-get --assume-yes --only-upgrade install linux-tools-common linux-libc-dev  base-files  dwarves
           if [ -f "build/_setup_env.sh" ]; then
-            sed -i 's#export PATH#export PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"#g' build/_setup_env.sh
+            sed -i "s#export PATH#export PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"#g" build/_setup_env.sh
             echo "The file build/_setup_env.sh existed and was patched."
-            echo $(grep 'export PATH.+' build/_setup_env.sh)
-            echo "CC = aarch64-linux-android$(echo ${{ inputs.android_version }} | sed 's/android1/3/g')-clang"
+            #echo $(grep -E 'export PATH.+' build/_setup_env.sh)
           else
             export PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"
+          fi
+          CC="aarch64-linux-android$(echo ${{ inputs.android_version }} | sed 's/android1/3/g')-clang"
+          echo -e "CC = ${CC}\nPATH :\necho $PATH"
+          if ! type $CC;then
+            echo "$CC Not found in the PATH !!!"
           fi
           
           if [ -f "build/build.sh" ]; then
             sed -i 's/-dirty//' ./common/scripts/setlocalversion
-            LTO=${{ inputs.lto_type }} BUILD_CONFIG=common/build.config.gki.aarch64 CC="aarch64-linux-android$(echo ${{ inputs.android_version }} | sed 's/android1/3/g')-clang" build/build.sh
+            LTO=${{ inputs.lto_type }} BUILD_CONFIG=common/build.config.gki.aarch64 CC=${CC} build/build.sh
           else
             rm -rf ./common/android/abi_gki_protected_exports_*
             sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
